name: bc-project-cpu-1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio
    - pyqt
    - pip:
        - moviepy
        - tensorflow==1.5.0
        - keras

